### PR TITLE
add download button inline with Definitions heading

### LINKED ISSUE #37: Download button
Add button that says "Download this data" below the ArcGIS web map that is just a hyperlink to here: https://opendata.arcgis.com/datasets/98a09bec89c84681ae1701a2eb62f599_0.csv

### PR DESCRIPTION
**Pull request by ckingbailey**
This resolves #37 

screenshot:
screen shot 2018-10-11 at 5 37 41 pm

### CODE REVIEW

**Comment by ckingbailey** [comment]
@dcgull here's it is with the download button.

I'm still not clear why we need the Definitions view to collapse

**Comment by ckingbailey** [comment]
* more information on this element in PR #44

**Comment by ckingbailey** [comment]
@dcgull I'm gonna go ahead merge this so I can at least call it "done enough" and deploy what's here.

If this is still not what you're picturing can you please paint me a better picture of what a panel between two buttons looks like, and why it needs to be collapsible if it's at the end of the page?

**Comment by dcgull** [comment]
Sorry for the delay in response. What I’m picturing is two buttons, one
above the other. When you press the top one, the hidden panel between them
opens like an accordion, keeping the download button on bottom.

**Comment by ckingbailey** [comment]
Ok, I get it now. Is it really better to push download button to bottom? Why not keep it up top next to the "About the data" heading?

I have a slight design tweak for that. I'll probably get to that this afternoon.

**Comment by dcgull** [comment]
This is all just my first thought, I am open to whatever you think will
look nice.

**Comment by dcgull** [comment]
@ckingbailey  Are we ready to go live? I need to record a video today showing off all this functionality.

**Pull request merged**
