### PR TITLE
layout story like in @dcgull pdf

### PR DESCRIPTION
**Pull request by ckingbailey**
resolves issue #33 

Lay out story to flow in a zig-zag kind of pattern:

screen shot 2018-10-03 at 6 24 08 pm

screen shot 2018-10-03 at 6 24 22 pm

screen shot 2018-10-03 at 6 24 33 pm

### CODE REVIEW

**Comment by dcgull** [comment]
Also, let's make the words "latest assessment" a hyperlink to the latest assessment: https://water.ca.gov/-/media/DWR-Website/Web-Pages/Programs/All-Programs/Division-of-safety-of-dams/Files/Publications/Dams-Within-Jurisdiction-of-the-State-of-California-2018-Alphabetically-by-Dam-Name.pdf

**Comment by ckingbailey** [comment]
Yeah, there is a size difference. They looked different-sized in the pdf. I can make them the same size.

Link, ok, I’ll add it. Same color as text, got it, but probably should change color on click and on mouse hover, yeah?

I’ll get on those items tonight around 5:30

**Comment by dcgull** [comment]
Ok, great, as soon as those two changes are ready lets merge.

**Comment by dcgull** [comment]
The size of the first map looks about right to me, so lets set the second map to match it. And can we center the first map bellow the text, instead of left justify?

**Pull request merged**
