### PR TITLE
add definitions table below map

### LINKED ISSUE #43: Definitions dropdown
@dsconstable wrote us a nice PDF of data definitions. @dcgull wants this turned into a dropdown below the map

TIP: Foundation probably has a ready made dropdown for us. Look it up.

### PR DESCRIPTION
**Pull request by ckingbailey**
Resolves #43 

I didn't make it collapsible because it's already at the end of page so I didn't see the point.

I made the colors match @dsconstable's pdf. I think the color palette looks good within the page.

Screenshots:
screen shot 2018-10-11 at 4 23 48 pm

Here's what it looks like next to the map:
screen shot 2018-10-11 at 4 24 00 pm

### CODE REVIEW

**Comment by dcgull** [comment]
Please do make it collapsable. Remember, we want to have "About this Data" and "Download this Data" as buttons, with this collapsable panel between them.

**Comment by ckingbailey** [comment]
I'm not picturing what you mean when you say the panel is between the buttons

**Comment by ckingbailey** [comment]
Isn't the download button just a link to a file, rather than a view of some content?

I was waiting on @jesrah for the download button, but I'll go ahead and do it since we're out of time

**Comment by ckingbailey** [comment]
I'm gonna go ahead and merge what's here and start another branch for the further refinements

**Pull request merged**
